apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: fintech-platform-catalog
  description: Catálogo de FinTech Peru S.A.
spec:
  targets:
    - https://github.com/JCFlores93/fintech-platform-catalog/blob/main/org/groups.yaml
    - https://github.com/JCFlores93/fintech-platform-catalog/blob/main/org/users.yaml
    - https://github.com/JCFlores93/fintech-platform-catalog/blob/main/systems/banca-digital.yaml
    - https://github.com/JCFlores93/fintech-platform-catalog/blob/main/systems/creditos.yaml
    - https://github.com/JCFlores93/fintech-platform-catalog/blob/main/systems/notificaciones.yaml
